disabled_rules: # rule identifiers to exclude from running
- line_length
- trailing_whitespace
- opening_brace
included: # paths to include during linting. `--path` is ignored if present.
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
